CREATE (GrandfatherByFather:Person {name: 'Grandfather by father'}),
       (GrandmotherByFather:Person {name: 'Grandmother by father'}),
       (GrandfatherByMother:Person {name: 'Grandfather by mother'}),
       (GrandmotherByMother:Person {name: 'Grandmother by mother'}),
       (Father:Person {name: 'Father'}),
       (Mother:Person {name: 'Mother'}),
       (Son:Person {name: 'Son'}),
       (Daughter:Person {name: 'Daughter'}),

       (GrandfatherByFather)-[:HUSBAND_OF]->(GrandmotherByFather),
       (GrandmotherByFather)-[:WIFE_OF]->(GrandfatherByFather),
       (GrandfatherByFather)-[:FATHER_OF]->(Father),
       (Father)-[:CHILD_OF]->(GrandfatherByFather),
       (GrandmotherByFather)-[:MOTHER_OF]->(Father),
       (Father)-[:CHILD_OF]->(GrandmotherByFather),

       (GrandfatherByMother)-[:HUSBAND_OF]->(GrandmotherByMother),
       (GrandmotherByMother)-[:WIFE_OF]->(GrandfatherByMother),
       (GrandfatherByMother)-[:FATHER_OF]->(Mother),
       (Mother)-[:CHILD_OF]->(GrandfatherByMother),
       (GrandmotherByMother)-[:MOTHER_OF]->(Mother),
       (Mother)-[:CHILD_OF]->(GrandmotherByMother),

       (Father)-[:HUSBAND_OF]->(Mother),
       (Mother)-[:WIFE_OF]->(Father),
       (Father)-[:FATHER_OF]->(Son),
       (Son)-[:CHILD_OF]->(Father),
       (Mother)-[:MOTHER_OF]->(Son),
       (Son)-[:CHILD_OF]->(Mother),
       (Father)-[:FATHER_OF]->(Daughter),
       (Daughter)-[:CHILD_OF]->(Father),
       (Mother)-[:MOTHER_OF]->(Daughter),
       (Daughter)-[:CHILD_OF]->(Mother);