CREATE (GrandfatherByFather:Person {name: 'Grandfather by father', sex: 'MALE'}),
       (GrandmotherByFather:Person {name: 'Grandmother by father', sex: 'FEMALE'}),
       (GrandfatherByMother:Person {name: 'Grandfather by mother', sex: 'MALE'}),
       (GrandmotherByMother:Person {name: 'Grandmother by mother', sex: 'FEMALE'}),
       (Father:Person {name: 'Father', sex: 'MALE'}),
       (Mother:Person {name: 'Mother', sex: 'FEMALE'}),
       (Son:Person {name: 'Son', sex: 'MALE'}),
       (Daughter:Person {name: 'Daughter', sex: 'FEMALE'}),

       (GrandfatherByFather)-[:SPOUSE_OF]->(GrandmotherByFather),
       (GrandmotherByFather)-[:SPOUSE_OF]->(GrandfatherByFather),
       (Father)-[:CHILD_OF]->(GrandfatherByFather),
       (Father)-[:CHILD_OF]->(GrandmotherByFather),

       (GrandfatherByMother)-[:SPOUSE_OF]->(GrandmotherByMother),
       (GrandmotherByMother)-[:SPOUSE_OF]->(GrandfatherByMother),
       (Mother)-[:CHILD_OF]->(GrandfatherByMother),
       (Mother)-[:CHILD_OF]->(GrandmotherByMother),

       (Father)-[:SPOUSE_OF]->(Mother),
       (Mother)-[:SPOUSE_OF]->(Father),
       (Son)-[:CHILD_OF]->(Father),
       (Son)-[:CHILD_OF]->(Mother),
       (Daughter)-[:CHILD_OF]->(Father),
       (Daughter)-[:CHILD_OF]->(Mother);