CREATE (GrandfatherByFather:Person {name: 'Grandfather by father', sex: 'MALE'}),
       (GrandmotherByFather:Person {name: 'Grandmother by father', sex: 'FEMALE'}),
       (GrandfatherByMother:Person {name: 'Grandfather by mother', sex: 'MALE'}),
       (GrandmotherByMother:Person {name: 'Grandmother by mother', sex: 'FEMALE'}),
       (Father:Person {name: 'Father', sex: 'MALE'}),
       (Mother:Person {name: 'Mother', sex: 'FEMALE'}),
       (Son:Person {name: 'Son', sex: 'MALE'}),
       (Daughter:Person {name: 'Daughter', sex: 'FEMALE'}),

       (GrandfatherByFather)-[:RELATES {name: 'SPOUSE'}]->(GrandmotherByFather),
       (GrandmotherByFather)-[:RELATES {name: 'SPOUSE'}]->(GrandfatherByFather),
       (Father)<-[:RELATES {name: 'PARENT'}]-(GrandfatherByFather),
       (Father)<-[:RELATES {name: 'PARENT'}]-(GrandmotherByFather),

       (GrandfatherByMother)-[:RELATES {name: 'SPOUSE'}]->(GrandmotherByMother),
       (GrandmotherByMother)-[:RELATES {name: 'SPOUSE'}]->(GrandfatherByMother),
       (Mother)<-[:RELATES {name: 'PARENT'}]-(GrandfatherByMother),
       (Mother)<-[:RELATES {name: 'PARENT'}]-(GrandmotherByMother),

       (Father)-[:RELATES {name: 'SPOUSE'}]->(Mother),
       (Mother)-[:RELATES {name: 'SPOUSE'}]->(Father),
       (Son)<-[:RELATES {name: 'PARENT'}]-(Father),
       (Son)<-[:RELATES {name: 'PARENT'}]-(Mother),
       (Daughter)<-[:RELATES {name: 'PARENT'}]-(Father),
       (Daughter)<-[:RELATES {name: 'PARENT'}]-(Mother);